**Name** : Shrutika Ipar
**Class **: SY-A
**Branch** : AI & DS
**Roll No** : A-38

#          PRACTICAL NO.3

**AIM** : Data Wrangling with pandas: Manipulate and transform data to suit the analysis needs.

**1. What is data wrangling, and why is it important before analysis?**

**ANS **: Data wrangling is the process of cleaning, transforming, and enriching raw data into a usable and appropriate format for analysis. It is important before analysis because it ensures data quality, accuracy, and consistency, which are essential for generating reliable insights and making informed decisions.

2.**You receive messy data with missing values, duplicates, and wrong types. What steps will you follow to clean it?**

**ANS** : When faced with messy data containing missing values, duplicates, and wrong data types, here are the general steps to follow for cleaning:

**Step 1: Understand the Data and Identify Issues**
*   **Load the Data:** Load the data into a suitable data structure (e.g., Pandas DataFrame in Python).
*   **Initial Inspection:** Use functions like `.info()`, `.describe()`, `.head()`, `.tail()` to get an overview of the data, column types, and basic statistics.
*   **Visualize Data:** Use plots (histograms, box plots) to identify outliers, skewed distributions, and potential errors.

**Step 2: Handle Missing Values**
*   **Identify Missing Values:** Use methods like `.isnull().sum()` to count missing values per column.
*   **Understand the Cause:** Determine if missing values are random, systematic, or due to data entry errors.
*   **Strategies for Handling Missing Values:**
    *   **Imputation:** Fill missing values with a statistical measure (mean, median, mode) for numerical data, or a common category for categorical data. Be cautious, as imputation can introduce bias.
    *   **Forward/Backward Fill:** For time-series or sequential data, fill missing values with the previous or next valid observation.
    *   **Deletion:** Remove rows or columns with a high percentage of missing values, but only if it doesn't lead to significant data loss or bias.
    *   **Advanced Techniques:** Use machine learning models (e.g., K-Nearest Neighbors imputation) for more sophisticated imputation.

**Step 3: Correct Data Types**
*   **Identify Incorrect Types:** Check column data types using `.info()`.
*   **Convert Types:** Convert columns to their correct data types (e.g., convert strings to numeric, objects to datetime, or numeric to categorical).
    *   Use `pd.to_numeric()`, `pd.to_datetime()`, `astype()`.
    *   Handle errors during conversion (e.g., `errors='coerce'` to turn unparseable values into NaN).

**Step 4: Remove Duplicate Data**
*   **Identify Duplicates:** Use `df.duplicated().sum()` to find duplicate rows.
*   **Decide on Duplicates:** Determine if duplicates are intentional or errors. Sometimes, partial duplicates (duplicates based on a subset of columns) need to be considered).
*   **Remove Duplicates:** Use `df.drop_duplicates()` to remove duplicate rows, keeping either the first or last occurrence.

**Step 5: Address Inconsistent Data and Formatting Issues**
*   **Text Data Cleaning:**
    *   **Standardize Case:** Convert text to lowercase or uppercase.
    *   **Remove Whitespace:** Trim leading/trailing spaces.
    *   **Correct Typos:** Use string methods (`.replace()`, regular expressions) or fuzzy matching for common misspellings.
    *   **Standardize Categories:** Ensure consistent naming for categorical variables (e.g., 'USA' vs 'U.S.A.' vs 'United States').
*   **Numerical Data Cleaning:**
    *   **Handle Outliers:** Identify and decide how to treat outliers (remove, cap, transform).
    *   **Standardize Units:** Ensure all numerical values in a column use the same unit (e.g., all in meters, not some in meters and some in centimeters).
*   **Date Data Cleaning:**
    *   **Standardize Formats:** Ensure all dates are in a consistent format.
    *   **Handle Invalid Dates:** Correct or remove dates that are out of a valid range.

**Step 6: Data Validation and Verification**
*   **Apply Business Rules:** Check if data conforms to known business rules or constraints.
*   **Cross-Reference:** Compare cleaned data with other reliable sources if available.
*   **Summarize Changes:** Keep track of the changes made during the cleaning process.

**Step 7: Document Cleaning Steps**
*   Maintain a clear record of all data cleaning steps taken. This ensures reproducibility and understanding for future analysis or team members.

3. **How can you check column names, data types, and summary statistics? What does "info()" show that "describe()" does not?**

**ANS** : **To check column names**, use `df.columns`.
**To check data types and non-null counts**, use `df.info()`. This shows non-null counts, data types, and memory usage, which `describe()` does not.
**To get summary statistics**, use `df.describe()`. This shows statistical measures (mean, std, min, max, quartiles) for numerical columns, and unique counts, top values for categorical columns, which `info()` does not.

 **4. How do you identify missing values and outliers in a dataset**?

 **ANS**  : **To identify missing values**, you can use `df.isnull().sum()`, `df.info()`, or visualize with heatmaps. For specific placeholders, use `df.replace()`.
**To identify outliers**, use statistical methods like **Z-score** (values beyond +/- 2 or 3 standard deviations) or the **IQR method** (values outside 1.5 * IQR from Q1/Q3). Visualization methods include **box plots**, histograms, and scatter plots.

5. **How do you reduce memory usage in pandas DataFrames?**

**ANS** : Reducing memory usage in pandas DataFrames is crucial for working with large datasets efficiently. Here are several effective strategies:

**1. Choose Appropriate Data Types (Downcasting):**
   *   Pandas often defaults to `int64` or `float64` for numerical columns and `object` for strings, which can be overkill for the actual range of values or cardinality. You can 'downcast' these to smaller types.
   *   **Integers:** If a column contains only integers between -128 and 127, it can be `int8` instead of `int64`.
   *   **Floats:** If precision is not paramount, `float32` can often replace `float64`.
   *   **Booleans:** Use `bool` type for true/false values.
   *   **Categorical Data:** For columns with a limited number of unique string values (e.g., 'Gender', 'Country'), converting them to the `category` data type can significantly reduce memory, as pandas stores an integer representation and a mapping of categories.

   ```python
   # Example of downcasting numerical types
   for col in df.select_dtypes(include=['int64']).columns:
       df[col] = pd.to_numeric(df[col], downcast='integer')
   for col in df.select_dtypes(include=['float64']).columns:
       df[col] = pd.to_numeric(df[col], downcast='float')

   # Example of converting to 'category' type
   for col in df.select_dtypes(include=['object']).columns:
       num_unique_values = len(df[col].unique())
       num_total_values = len(df[col])
       if num_unique_values / num_total_values < 0.5: # A heuristic: if unique values are less than 50% of total values
           df[col] = df[col].astype('category')
   ```

**2. Use `read_csv` Parameters Effectively:**
   *   When loading data, you can specify data types directly using the `dtype` parameter, preventing pandas from inferring potentially larger types.
   *   `usecols`: Load only the columns you need.
   *   `chunksize`: Process large files in chunks to avoid loading the entire file into memory at once.

   ```python
   # Example specifying dtypes during loading
   # df = pd.read_csv('your_data.csv', dtype={'col_int': 'int16', 'col_float': 'float32', 'col_cat': 'category'})
   ```

**3. Remove Unnecessary Columns:**
   *   If certain columns are not used for analysis, drop them to free up memory.

   ```python
   # df.drop(columns=['unnecessary_column_1', 'unnecessary_column_2'], inplace=True)
   ```

**4. Optimize String Columns:**
   *   As mentioned, converting `object` (string) columns with low cardinality to `category` is very effective.
   *   For string columns with high cardinality (many unique strings), if they are purely textual and not used for direct filtering or grouping, they will remain as `object` dtype, which consumes more memory. There isn't a direct 'downcast' for high-cardinality strings like there is for numbers, but you can consider techniques like:
      *   **Hashing/Encoding:** If strings are identifiers, convert them to numerical IDs.
      *   **Text Compression:** If applicable, store raw text outside the DataFrame or use specialized libraries.

**5. Handle Missing Values Carefully:**
   *   Missing values (NaN) for numerical columns convert them to `float64` if the original column was integer, as `NaN` is a float. If you can use `pd.NA` (introduced in pandas 1.0) with integer types (e.g., `Int64`, `Int32`), it allows for integer arrays with missing values, which can save memory compared to converting to float.

   ```python
   # Example using nullable integer type
   # df['integer_column_with_na'] = df['integer_column_with_na'].astype('Int64') # Note the capital 'I'
   ```

**6. Delete Original DataFrames and Run Garbage Collection:**
   *   After creating new, optimized DataFrames, delete the original larger ones and explicitly run Python's garbage collector.

   ```python
   # del original_df
   # import gc
   # gc.collect()
   ```

**7. Avoid Chained Indexing (SettingWithCopyWarning):**
   *   While not directly memory optimization, avoiding chained indexing can prevent pandas from creating unnecessary copies of DataFrames or Series, which indirectly helps manage memory.

**Monitoring Memory Usage:**
   *   Use `df.info(memory_usage='deep')` to get a detailed breakdown of memory usage, including the actual memory consumed by `object` (string) columns.

**Conclusion **:

Data wrangling is a fundamental process in data analysis, involving cleaning, transforming, and enriching raw data to make it suitable for insightful analysis. This notebook effectively demonstrated a comprehensive suite of data wrangling techniques using pandas, including: identifying and handling missing values and duplicates, correcting data types, filtering and sorting data, performing aggregations, merging and joining DataFrames, reshaping data with pivot and melt operations, and advanced time-series manipulations. These skills are crucial for ensuring data quality, consistency, and usability, thereby enabling more accurate and reliable analytical outcomes

# Data Wrangling with Pandas: Practical Exercises

In [ ]:
import pandas as pd
import numpy as np

# Sample DataFrame for demonstrations
data = {
    'A': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'B': ['apple', 'banana', 'orange', 'apple', 'banana', 'orange', 'apple', 'banana', 'orange', 'apple'],
    'C': [10.1, 20.2, 5.5, 12.3, 8.7, 15.0, 11.2, 9.5, 18.1, 7.3],
    'D': ['X', 'Y', 'X', 'Z', 'Y', 'X', 'Z', 'Y', 'X', 'Z'],
    'E': pd.to_datetime(['2023-01-01', '2023-01-02', '2023-01-01', '2023-01-03', '2023-01-02',
                         '2023-01-03', '2023-01-01', '2023-01-02', '2023-01-03', '2023-01-01']),
    'F': [100, 150, 120, 200, 130, 180, 110, 160, 140, 190],
    'G': [np.nan, 1, 2, np.nan, 3, 4, np.nan, 5, 6, np.nan]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
display(df)

Original DataFrame:

    A       B     C  D          E    F    G
0   1   apple  10.1  X 2023-01-01  100  NaN
1   2  banana  20.2  Y 2023-01-02  150  1.0
2   3  orange   5.5  X 2023-01-01  120  2.0
3   4   apple  12.3  Z 2023-01-03  200  NaN
4   5  banana   8.7  Y 2023-01-02  130  3.0
5   6  orange  15.0  X 2023-01-03  180  4.0
6   7   apple  11.2  Z 2023-01-01  110  NaN
7   8  banana   9.5  Y 2023-01-02  160  5.0
8   9  orange  18.1  X 2023-01-03  140  6.0
9  10   apple   7.3  Z 2023-01-01  190  NaN

## Weak Students (Basic)

### 1. Select a single column from a DataFrame.

In [ ]:
print("Selecting column 'A':")
display(df['A'])

Selecting column 'A':

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: A, dtype: int64

### 2. Add a new column with constant values.

In [ ]:
df['New_Constant_Col'] = 100
print("DataFrame with 'New_Constant_Col':")
display(df.head())

DataFrame with 'New_Constant_Col':

   A       B     C  D          E    F    G  New_Constant_Col
0  1   apple  10.1  X 2023-01-01  100  NaN               100
1  2  banana  20.2  Y 2023-01-02  150  1.0               100
2  3  orange   5.5  X 2023-01-01  120  2.0               100
3  4   apple  12.3  Z 2023-01-03  200  NaN               100
4  5  banana   8.7  Y 2023-01-02  130  3.0               100

### 3. Sort a DataFrame by one column.

In [ ]:
df_sorted = df.sort_values(by='C', ascending=False)
print("DataFrame sorted by column 'C' (descending):")
display(df_sorted.head())

DataFrame sorted by column 'C' (descending):

   A       B     C  D          E    F    G  New_Constant_Col
1  2  banana  20.2  Y 2023-01-02  150  1.0               100
8  9  orange  18.1  X 2023-01-03  140  6.0               100
5  6  orange  15.0  X 2023-01-03  180  4.0               100
3  4   apple  12.3  Z 2023-01-03  200  NaN               100
6  7   apple  11.2  Z 2023-01-01  110  NaN               100

### 4. Rename DataFrame columns.

In [ ]:
df_renamed = df.rename(columns={'A': 'Column_Alpha', 'B': 'Column_Beta'})
print("DataFrame with renamed columns:")
display(df_renamed.head())

DataFrame with renamed columns:

   Column_Alpha Column_Beta     C  D          E    F    G  New_Constant_Col
0             1       apple  10.1  X 2023-01-01  100  NaN               100
1             2      banana  20.2  Y 2023-01-02  150  1.0               100
2             3      orange   5.5  X 2023-01-01  120  2.0               100
3             4       apple  12.3  Z 2023-01-03  200  NaN               100
4             5      banana   8.7  Y 2023-01-02  130  3.0               100

### 5. Display summary statistics using describe().

In [ ]:
print("Summary statistics for numerical columns:")
display(df.describe())

Summary statistics for numerical columns:

,A,C,E,F,G,New_Constant_Col
count,10.00000,10.000000,10,10.000000,6.000000,10.0
mean,5.50000,11.790000,2023-01-01 21:36:00,148.000000,3.500000,100.0
min,1.00000,5.500000,2023-01-01 00:00:00,100.000000,1.000000,100.0
25%,3.25000,8.900000,2023-01-01 00:00:00,122.500000,2.250000,100.0
50%,5.50000,10.650000,2023-01-02 00:00:00,145.000000,3.500000,100.0
75%,7.75000,14.325000,2023-01-02 18:00:00,175.000000,4.750000,100.0
max,10.00000,20.200000,2023-01-03 00:00:00,200.000000,6.000000,100.0
std,3.02765,4.700225,NaN,34.253954,1.870829,0.0

## Normal Students (Moderate)

### 6. Filter rows using multiple conditions.

In [ ]:
filtered_df = df[(df['A'] > 5) & (df['B'] == 'orange')]
print("Filtered DataFrame (A > 5 AND B == 'orange'):")
display(filtered_df)

Filtered DataFrame (A > 5 AND B == 'orange'):

   A       B     C  D          E    F    G  New_Constant_Col
5  6  orange  15.0  X 2023-01-03  180  4.0               100
8  9  orange  18.1  X 2023-01-03  140  6.0               100

### 7. Group data by a categorical column and calculate mean.

In [ ]:
grouped_df = df.groupby('B')['C'].mean().reset_index()
print("Mean of column 'C' grouped by 'B':")
display(grouped_df)

Mean of column 'C' grouped by 'B':

        B          C
0   apple  10.225000
1  banana  12.800000
2  orange  12.866667

### 8. Merge two DataFrames on a common column.

In [ ]:
df2_data = {'B': ['apple', 'banana', 'grape'], 'Value_from_df2': [1000, 2000, 3000]}
df2 = pd.DataFrame(df2_data)

print("DataFrame 1 (original df head):")
display(df.head())
print("DataFrame 2:")
display(df2)

merged_df = pd.merge(df, df2, on='B', how='left')
print("Merged DataFrame (left merge on 'B'):")
display(merged_df.head())

DataFrame 1 (original df head):

   A       B     C  D          E    F    G  New_Constant_Col
0  1   apple  10.1  X 2023-01-01  100  NaN               100
1  2  banana  20.2  Y 2023-01-02  150  1.0               100
2  3  orange   5.5  X 2023-01-01  120  2.0               100
3  4   apple  12.3  Z 2023-01-03  200  NaN               100
4  5  banana   8.7  Y 2023-01-02  130  3.0               100

DataFrame 2:

        B  Value_from_df2
0   apple            1000
1  banana            2000
2   grape            3000

Merged DataFrame (left merge on 'B'):

   A       B     C  D          E    F    G  New_Constant_Col  Value_from_df2
0  1   apple  10.1  X 2023-01-01  100  NaN               100          1000.0
1  2  banana  20.2  Y 2023-01-02  150  1.0               100          2000.0
2  3  orange   5.5  X 2023-01-01  120  2.0               100             NaN
3  4   apple  12.3  Z 2023-01-03  200  NaN               100          1000.0
4  5  banana   8.7  Y 2023-01-02  130  3.0               100          2000.0

### 9. Drop rows and columns using pandas functions.

In [ ]:
df_dropped_row = df.drop(index=[0, 1]) # Drop first two rows
df_dropped_col = df.drop(columns=['C', 'G']) # Drop columns 'C' and 'G'

print("DataFrame after dropping rows 0 and 1:")
display(df_dropped_row.head())
print("DataFrame after dropping columns 'C' and 'G':")
display(df_dropped_col.head())

DataFrame after dropping rows 0 and 1:

   A       B     C  D          E    F    G  New_Constant_Col
2  3  orange   5.5  X 2023-01-01  120  2.0               100
3  4   apple  12.3  Z 2023-01-03  200  NaN               100
4  5  banana   8.7  Y 2023-01-02  130  3.0               100
5  6  orange  15.0  X 2023-01-03  180  4.0               100
6  7   apple  11.2  Z 2023-01-01  110  NaN               100

DataFrame after dropping columns 'C' and 'G':

   A       B  D          E    F  New_Constant_Col
0  1   apple  X 2023-01-01  100               100
1  2  banana  Y 2023-01-02  150               100
2  3  orange  X 2023-01-01  120               100
3  4   apple  Z 2023-01-03  200               100
4  5  banana  Y 2023-01-02  130               100

### 10. Apply a simple function to a column.

In [ ]:
df['C_multiplied_by_2'] = df['C'].apply(lambda x: x * 2)
print("DataFrame with 'C_multiplied_by_2' column:")
display(df.head())

DataFrame with 'C_multiplied_by_2' column:

,A,B,C,D,E,F,G,New_Constant_Col,C_multiplied_by_2
0,1,apple,10.1,X,2023-01-01,100,NaN,100,20.2
1,2,banana,20.2,Y,2023-01-02,150,1.0,100,40.4
2,3,orange,5.5,X,2023-01-01,120,2.0,100,11.0
3,4,apple,12.3,Z,2023-01-03,200,NaN,100,24.6
4,5,banana,8.7,Y,2023-01-02,130,3.0,100,17.4

## Bright Students (Advanced)

### 11. Perform pivot and melt operations on a dataset.

In [ ]:
# Pivot: Reshape data based on column values
df_pivot = df.pivot_table(index='D', columns='B', values='A', aggfunc='sum')
print("Pivot Table (sum of 'A' by 'D' and 'B'):")
display(df_pivot)

# Melt: Unpivot a DataFrame from wide to long format
df_melt = df.melt(id_vars=['A', 'B'], value_vars=['C', 'F'], var_name='Metric', value_name='Value')
print("Melted DataFrame (unpivoting 'C' and 'F'):")
display(df_melt.head())

Pivot Table (sum of 'A' by 'D' and 'B'):

B  apple  banana  orange
D
X    1.0     NaN    18.0
Y    NaN    15.0     NaN
Z   21.0     NaN     NaN

Melted DataFrame (unpivoting 'C' and 'F'):

   A       B Metric  Value
0  1   apple      C   10.1
1  2  banana      C   20.2
2  3  orange      C    5.5
3  4   apple      C   12.3
4  5  banana      C    8.7

### 12. Implement multilevel indexing.

In [ ]:
df_multi_index = df.set_index(['B', 'D'])
print("DataFrame with MultiIndex on 'B' and 'D':")
display(df_multi_index.head())

print("\nSelecting data for ('apple', 'X') from MultiIndex:")
display(df_multi_index.loc[('apple', 'X')])

DataFrame with MultiIndex on 'B' and 'D':

          A     C          E    F    G  New_Constant_Col  C_multiplied_by_2
B      D
apple  X  1  10.1 2023-01-01  100  NaN               100               20.2
banana Y  2  20.2 2023-01-02  150  1.0               100               40.4
orange X  3   5.5 2023-01-01  120  2.0               100               11.0
apple  Z  4  12.3 2023-01-03  200  NaN               100               24.6
banana Y  5   8.7 2023-01-02  130  3.0               100               17.4

Selecting data for ('apple', 'X') from MultiIndex:

/tmp/ipykernel_1743/1695903456.py:6: PerformanceWarning: indexing past lexsort depth may impact performance.
  display(df_multi_index.loc[('apple', 'X')])

         A     C          E    F   G  New_Constant_Col  C_multiplied_by_2
B     D
apple X  1  10.1 2023-01-01  100 NaN               100               20.2

### 13. Compare merge v/s join operations.

In [ ]:
df_left = pd.DataFrame({'key': ['A', 'B', 'C', 'D'], 'value_left': np.random.randint(1, 10, 4)})
df_right = pd.DataFrame({'key': ['B', 'D', 'E', 'F'], 'value_right': np.random.randint(10, 20, 4)})

print("DataFrame Left:")
display(df_left)
print("DataFrame Right:")
display(df_right)

# Merge (explicit columns)
merged_df_ex = pd.merge(df_left, df_right, on='key', how='inner')
print("\nMerged DataFrame (inner merge on 'key' column):")
display(merged_df_ex)

# Join (index-based)
df_left_indexed = df_left.set_index('key')
df_right_indexed = df_right.set_index('key')
joined_df = df_left_indexed.join(df_right_indexed, how='inner')
print("\nJoined DataFrame (inner join on index):")
display(joined_df)

print("\nExplanation: `merge()` is a function that can merge DataFrames based on columns or indices (explicitly specified) and is more flexible for various types of joins (one-to-one, many-to-one, many-to-many). `join()` is a method primarily used for merging DataFrames based on their indices, though it can take an 'on' parameter for column-based joins. For complex joining criteria, `merge()` is generally preferred.")

DataFrame Left:

  key  value_left
0   A           7
1   B           5
2   C           8
3   D           4

DataFrame Right:

  key  value_right
0   B           11
1   D           15
2   E           12
3   F           15

Merged DataFrame (inner merge on 'key' column):

  key  value_left  value_right
0   B           5           11
1   D           4           15

Joined DataFrame (inner join on index):

     value_left  value_right
key
B             5           11
D             4           15

Explanation: `merge()` is a function that can merge DataFrames based on columns or indices (explicitly specified) and is more flexible for various types of joins (one-to-one, many-to-one, many-to-many). `join()` is a method primarily used for merging DataFrames based on their indices, though it can take an 'on' parameter for column-based joins. For complex joining criteria, `merge()` is generally preferred.

### 14. Create custom aggregation functions.

In [ ]:
def range_agg(series):
    return series.max() - series.min()

custom_agg_df = df.groupby('B')['C'].agg(['min', 'max', 'mean', range_agg])
print("DataFrame with custom aggregation (range_agg on 'C' by 'B'):")
display(custom_agg_df)

DataFrame with custom aggregation (range_agg on 'C' by 'B'):

        min   max       mean  range_agg
B
apple   7.3  12.3  10.225000        5.0
banana  8.7  20.2  12.800000       11.5
orange  5.5  18.1  12.866667       12.6

### 15. Perform time series based data wrangling.

In [ ]:
# Set 'E' as the DataFrame index and sort it for time-series operations
df_ts = df.set_index('E').sort_index()
print("Original DataFrame with time index:")
display(df_ts)

# Resample daily and sum 'F'
df_resampled_daily = df_ts.resample('D')['F'].sum().reset_index()
print("\nResampled Daily Sum of 'F':")
display(df_resampled_daily)

# Calculate a 2-day rolling mean for 'F'
df_ts['F_rolling_mean'] = df_ts['F'].rolling('2D').mean()
print("\nDataFrame with 2-day rolling mean for 'F':")
display(df_ts)

Original DataFrame with time index:

             A       B     C  D    F    G  New_Constant_Col  C_multiplied_by_2
E
2023-01-01   1   apple  10.1  X  100  NaN               100               20.2
2023-01-01   3  orange   5.5  X  120  2.0               100               11.0
2023-01-01   7   apple  11.2  Z  110  NaN               100               22.4
2023-01-01  10   apple   7.3  Z  190  NaN               100               14.6
2023-01-02   2  banana  20.2  Y  150  1.0               100               40.4
2023-01-02   5  banana   8.7  Y  130  3.0               100               17.4
2023-01-02   8  banana   9.5  Y  160  5.0               100               19.0
2023-01-03   4   apple  12.3  Z  200  NaN               100               24.6
2023-01-03   6  orange  15.0  X  180  4.0               100               30.0
2023-01-03   9  orange  18.1  X  140  6.0               100               36.2

Resampled Daily Sum of 'F':

           E    F
0 2023-01-01  520
1 2023-01-02  440
2 2023-01-03  520

DataFrame with 2-day rolling mean for 'F':

,A,B,C,D,F,G,New_Constant_Col,C_multiplied_by_2,F_rolling_mean
E,,,,,,,,,
2023-01-01,1,apple,10.1,X,100,NaN,100,20.2,100.000000
2023-01-01,3,orange,5.5,X,120,2.0,100,11.0,110.000000
2023-01-01,7,apple,11.2,Z,110,NaN,100,22.4,110.000000
2023-01-01,10,apple,7.3,Z,190,NaN,100,14.6,130.000000
2023-01-02,2,banana,20.2,Y,150,1.0,100,40.4,134.000000
2023-01-02,5,banana,8.7,Y,130,3.0,100,17.4,133.333333
2023-01-02,8,banana,9.5,Y,160,5.0,100,19.0,137.142857
2023-01-03,4,apple,12.3,Z,200,NaN,100,24.6,160.000000
2023-01-03,6,orange,15.0,X,180,4.0,100,30.0,164.000000
2023-01-03,9,orange,18.1,X,140,6.0,100,36.2,160.000000